print("Welcome to xmas")
import time ; time.sleep(3)
print("")
print("FOLLOW ME")
print("""SNAPCHAT:gxreguy
instagram:xmlven""")
import time ; time.sleep(3)
usr=input('Enter Email Id:')  

pwd=input('Enter Password:')  
print("————")
import time ; time.sleep(3)
print("Hello, " + usr)
import time ; time.sleep(3)
print("———-")
print("did you just get trolled?")
import time ; time.sleep(3)
print(">              <")
print(" >            <")
print("  >          <")
print("   >        <")
print("    >      <")
print("     >    <")
print("      >  <")
print("       ><")
print("      >  <")
print("     >     <")
print("    >       <")
print("   >         <")
print("  >           <")
print(" >             <")
print(">               <")

print("M. A. S.  YESSSSSSSS")
import time ; time.sleep(3)
name=input('write your name:')
import time ; time.sleep(2)
print("")
print("Give us a sec while we type your name into a sentence...")
print("")
import time ; time.sleep(2)
print("did you know this dudes a bitch. who you ask? " + name)
import time ; time.sleep(2)
print("")
print("This tool is for fun. we will update it and add more stuff to it soon! such as hacking tools")
print("")
import time ; time.sleep(2)
